name: Upload JSON

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy PEPEISDED subasset JSON to S3 bucket
        run: aws s3 cp pepeisded-subasset.json s3://public-scarce-city --acl public-read
      - name: Deploy Bitgirls feed JSON to S3 bucket
        run: aws s3 cp bitgirls-feed.json s3://public-scarce-city --acl public-read
      - name: Deploy Memorychain feed JSON to S3 bucket
        run: aws s3 cp memorychain-feed.json s3://public-scarce-city --acl public-read
      - name: Deploy Oasis Mining feedJSON to S3 bucket
        run: aws s3 cp oasis-mining-feed.json s3://public-scarce-city --acl public-read
